demo_point:
- 0.22242
- -0.275048
- 0.00709
garment_config:
  garment_ori:
  - 0.47366
  - -0.32437
  - -0.46264
  - -0.67557
  garment_path: /home/sim/GarmentLab/Assets/Garment/Dress/Long_ShortSleeve/DLSS_Dress182/DLSS_Dress182_obj.usd
  garment_pos:
  - -0.15
  - 0
  - 0.15
  garment_scale:
  - 0.006
  - 0.006
  - 0.006
garment_name: dress0
target_point:
- 0.22242
- -0.275048
- 1.00709
task_name: hang
