demo_point:
- 0.66891
- 0.06105
- 0.02315
garment_config:
  garment_ori:
  - 0.71567
  - -0.28235
  - -0.41997
  - -0.48138
  garment_path: /home/sim/GarmentLab/Assets/Garment/Dress/Short_ShortSleeve/DSSS_Dress273/DSSS_Dress273_obj.usd
  garment_pos:
  - -0.23963
  - -0.27982
  - 0.32647
  garment_scale:
  - 0.0065
  - 0.0065
  - 0.0065
garment_name: dress1
target_point:
- 0.41957
- -0.01923
- 0.84274
task_name: hang
