demo_point:
- 0.65104
- -0.08206
- 0.0267
garment_config:
  garment_ori:
  - 0.72724
  - -0.12573
  - -0.28992
  - -0.60931
  garment_path: /home/sim/GarmentLab/Assets/Garment/Dress/Long_ShortSleeve/DLSS_dress144/DLSS_dress144_obj.usd
  garment_pos:
  - -0.3138
  - -0.27982
  - 0.32647
  garment_scale:
  - 0.007
  - 0.007
  - 0.007
garment_name: dress3
target_point:
- 0.41957
- -0.01923
- 0.84274
task_name: hang
