demo_point:
- 0.72186
- -0.04595
- 0.01918
garment_config:
  garment_ori:
  - 0.76165
  - -0.10855
  - -0.29678
  - -0.5657
  garment_path: /home/user/GarmentLab/Assets/Garment/Dress/Short_LongSleeve/DSLS_Dress329/DSLS_Dress329_obj.usd
  garment_pos:
  - -0.02171
  - -0.27982
  - 0.32647
  garment_scale:
  - 0.0055
  - 0.005
  - 0.005
garment_name: dress5
target_point:
- 0.41957
- -0.01923
- 0.84274
task_name: hang
